## Secret untuk kredensial MongoDB
# Gunakan key `MONGO_ROOT_USERNAME` dan `MONGO_ROOT_PASSWORD` berisi base64
# Sesuai permintaan: MONGO_ROOT_USERNAME = admin, MONGO_ROOT_PASSWORD = supersecretpassword
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # base64(admin) = YWRtaW4=
  MONGO_ROOT_USERNAME: YWRtaW4=
  # base64(supersecretpassword) = c3VwZXJzZWNyZXRwYXNzd29yZA==
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
