## Service untuk Prometheus
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  # type: NodePort agar Prometheus bisa diakses dari luar cluster
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      # port: port Service di dalam cluster
      port: 9090
      # targetPort: port di dalam Pod Prometheus
      targetPort: 9090
      # nodePort: akses dari luar cluster via <NodeIP>:30090
      nodePort: 30090
